name: "Setup Python and uv"
description: "Set up Python, install uv, and sync dependencies"
inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.14"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-extras
